{% set version = "0.2.1" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-dimred
  version: {{ version|replace("-", "_") }}

source:
  fn: dimRed_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/dimRed_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/dimRed/dimRed_{{ version }}.tar.gz
  sha256: 769b3a5a240c0a66ab853f7de370c2bd561199ef55fab17d53e706a0ff3ce41c

build:
  noarch: generic
  merge_build_host: True  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-drr
  run:
    - r-base
    - r-drr

test:
  commands:
    - $R -e "library('dimRed')"           # [not win]
    - "\"%R%\" -e \"library('dimRed')\""  # [win]

about:
  home: https://github.com/gdkrmr/dimRed
  license: GPL-3
  summary: A collection of dimensionality reduction techniques from R packages and provides a
    common interface for calling the methods.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
