appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: K1A76xxkdQCemAxW+pKvqzvph3+42dDablTzkYn1mODj8m0anZxquRgLI2ZoRVUfCIJH5PgIysshkPdiA4+0solJo+w6dTr68ivTB5z3rQbWdDWWeYdQTiciYTBb88onGRLJr5BuCLL2ePuElFTR8QziA42m5llJRWhnRN86pcSa4yT+eaxROaP64w81QEPnLVwFj1z6QDJFDEVLLFkogA6ou4clPtKWLsHTzrC9EK2S4v2q2kzIAY3S0su8ieOYUy18QSBV2mhwxQFGLHa46MiF1k6v23Ihn3a58kr64G1coa3binwbBE2+X/Qe0HgMNBosfbphWBpQHhPC9P5JGG2EfPugfaeA6qXwiCQN/PRD+JNHYwP5h7aetQjKdSq6xTzQcMY+bkxdVQXI0ZrhT/cE84el+M+AEYQgSTuCN6AfBPPAF6s901lusXgXtxJzbqQg3EoBwzkSlHyC8zArqDW5JzMl01CAP4UFwHCdCqk7bI7YoFDgQLcxZomAu4JnM1HN6E+XXGH0cOWNqACB/ghi2Kyn6JPPAcRnwfKOlsRs/uA3k2nTXt0zDnTemAnauK877W8nHU1PgEffHbwZbHiPQQzSCMLTsWs3xQpIcJbdSgVnXb0BlUfbBECM6NoIwU3CPQnZtVnXXBtri8dgUvch9qEXFXOKPYG/lNg4ypw=}
bot:
  automerge: true
