travis:
  secure:
    BINSTAR_TOKEN: OLkZ1sytAMZIDrrobdbD0vAib+IQDVHD985pYIyo8OVAY9ceDEG5JmD5G4nlpbeqbiozEqNY/2TVB1N1rU4N+wHtF4v39IF/ecuGesu6nyRnY7qJDccWQBf2DaFM0WxzuCmHq1+UL8cTzrM9JFHWnBFHpduQpEEAjauamr3wlXjJG4tC4kojNyORtiaVKxBuhkFrIggUjsJ/ojHQm5myshx1Cz/dY4mSF9hEB40veBAZkpBJxF6VVqielD9tExbeZasVO4TQ/RMyXrjGaH/BjvLF6edWSdgg3NXKstccHR9RLhKshTmPlxmSg8SucZv1IwsNYpbGhSyCvbbkQcXTTLvy1yyDEugiSJGcQRqS6A2mSU0maQ45Dp7qXI5DT+jcygZ8sdrZFeY2lYWe4B8LMU3bsBar+7Vq11LfpRK6WuKJxWrqB0i1r61c5+6713B9nV9Nng61B0ui7c7SBoR2nKIwdttQmD74poztNb2J7eAVwtjh6EW1aAe4Lm9PqoeE938M3C7knBeyOGL0562esiWtR7lKYtHRTw/pPDMajV8jIfrdbPkD8LTREgEma1pBwWsXhmF4I9TuynmD6MNiRIeHYJ4dufMzd00MvqDisV/ZGFxIQUrLcxzd3CBnAWFC5VNH9iHa0Kqid0szVJHg0tfnrwgD49NTqivqhefTnXY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
