travis:
  secure:
    BINSTAR_TOKEN: UdgffKLOwfiQQyZwj2r57v06COcLIeYc4ce/ncyEd7OUwZkIJPpEMzX/wa5kKajKZnVQWFThpAadc8zItF8nj4annpyDaPUg2ehUrd8MYvjq2C1tZVQY0mrdSwSab4oXW6r36a8j1IvhyTMtOYXK5QDvbr544bGpNilGl22olxBHhYc7A8P5STu2l+hQa/tpX1fgzpMjkh7B9Ggf35M/RUbkYzgqgxFcJjQgjJMJjSJa0/SmK4LITXu+Gci3lknbpJw4X9F2wdBYWWEKzm5elimC/24Dvj3MpkR6bLmSTsR1nx0rBJXPfhfY5p7ITHH8cqWWl2QSCoFNpTcE8A3YzUqR9nkDjeTySA9UblW7PdykZWruN5HAMYXVSJrbN1NJ2P6ZbxuxYBfxeJxpyh86l0xtxlkbUhisj01rFIh7DhGiw1Z5+Wdoh5YXCudBISzRRujgVmjxwXN09gvvXHxJQlgbRDS7SFMGxRFNxeg+XRyBc5NE/vHo3vRElDDFwBKnfdSsSXurumwxbvVZcG9PkQf5dZNyhFpLPuuHo9y06AJBsHiCG8gzurEGRkwZysxXhtrTonnTZ1KiNNhfd5dQluMBgEKnRlXT8jMmfE+m52iFcXFg4LDY7FUO9AdUISar2d2/wTfG1li5Xu+gN/nb61YVWae2+kcmkRuCpCIQzjQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
